; ESP32 IR Remote — điều khiển TV / điều hòa / quạt qua hồng ngoại
[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
lib_deps      =
  bblanchon/ArduinoJson@^7.3.0
  crankyoldgit/IRremoteESP8266@^2.8.6
monitor_speed = 115200
upload_speed  = 921600
upload_port   = COM6
build_flags            = -Wall
board_build.filesystem = littlefs

